@Users_Api = http://localhost:5001/users-api
@Products_Api = http://localhost:5001/products-api

GET {{Users_Api}}/users/
Accept: application/json
###
GET {{Users_Api}}/users/1
Accept: application/json

###

GET {{Products_Api}}/products/
Accept: application/json
###
GET {{Products_Api}}/products/2
Accept: application/json
